# Taller Árboles de Decisión

> Daniela A. Herrera Fandiño

> Octubre 2022

# Árbol de decisión

Según el siguiente árbol de decisión, analice y responda:

![Obama-Clinton decision tree](https://github.com/justmarkham/DAT8/raw/226791169b1cc6df8e8845c12e34e748d5ffaa85/notebooks/images/obama_clinton_tree.jpg)

## 1.1 ¿Qué son las observaciones? ¿Cuántas observaciones hay?


Ganador por **condados** considerado como las observaciones.



*   Cantidad de observaciones : 7




## 1.2 ¿Cuál es la variable de respuesta?


Preferencia de la población hacia un candidato,considerando diferentes características.

## 1.3 ¿Cuáles son las características?¿Cuál es la característica más predictiva?


  SEGREGAR INFO
  
Dentro de este árbol de decision se consideran características como tasa de graduacion, ubicacion geografica del condado, porcentaje de hogares pobres, densidad de la poblacion, repercucion politica de una eleccion anterior y poblacion de **color** en condados siendo esta la mas **predictiva**.

## 1.4 ¿Cuál es la predicción de clase para el siguiente condado con los siguientes datos: 15% de afroamericanos, 90% de tasa de graduación en la escuela secundaria, ubicado en el Sur, alta pobreza, alta densidad de población?


Obama gana estos condados ***185*** a ***36***

## 1.5 ¿Cuál es el chance predicha para ese mismo condado anteriormente descrito?

 Obama 185 vs 36

La probabilidad que Obama gane:

In [1]:
185/(185+36)

0.8371040723981901

El chance de que Obama gane:

In [2]:
185/(36) #chance 

5.138888888888889

## SVM


Para esta tarea consideramos un conjunto de observaciones sobre una serie de variedades de vino tinto y blanco que implican sus propiedades químicas y su clasificación por parte de los catadores. La industria del vino ha experimentado un gran crecimiento en los últimos tiempos debido al aumento del consumo social. El precio del vino depende de un concepto bastante abstracto de apreciación del vino por parte de los catadores, cuya opinión puede tener un alto grado de variabilidad. El precio del vino depende en cierta medida de este factor tan volátil. Otro factor clave en la certificación y evaluación de la calidad del vino son las pruebas fisicoquímicas, que se realizan en laboratorio y tienen en cuenta factores como la acidez, el nivel de pH, la presencia de azúcar y otras propiedades químicas. Para el mercado del vino, sería interesante que la calidad humana de la cata pudiera relacionarse con las propiedades químicas del vino para que el proceso de certificación y evaluación de la calidad estuviera más controlado.

Se dispone de dos conjuntos de datos, uno de los cuales se refiere al vino tinto y cuenta con 1.599 variedades diferentes, y el otro, al vino blanco, con 4.898 variedades. Todos los vinos se producen en una zona concreta de Portugal. Se recogen datos sobre 12 propiedades diferentes de los vinos, una de las cuales es la calidad, basada en datos sensoriales, y el resto son propiedades químicas de los vinos, como la densidad, la acidez, el contenido de alcohol, etc. Todas las propiedades químicas de los vinos son variables continuas. La calidad es una variable ordinal con una clasificación posible de 1 (peor) a 10 (mejor). Cada variedad de vino es catada por tres catadores independientes y la clasificación final asignada es la mediana de la clasificación dada por los catadores.

Se espera que un modelo predictivo desarrollado a partir de estos datos sirva de orientación a los viñedos en cuanto a la calidad y el precio que se espera obtener de sus productos sin depender en gran medida de la volatilidad de los catadores.


In [27]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import roc_auc_score, accuracy_score, make_scorer, roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC




In [4]:
data_r = pd.read_csv('https://raw.githubusercontent.com/prof-tatiana-gutierrez/DatosMD/master/Wine_data_red.csv')
data_w = pd.read_csv('https://raw.githubusercontent.com/prof-tatiana-gutierrez/DatosMD/master/Wine_data_white.csv')

In [5]:
data = data_w.assign(type = 'white')

data = data.append(data_r.assign(type = 'red'), ignore_index=True)
data.sample(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
2362            6.5              0.18         0.29             1.7      0.035   
4304            6.1              0.24         0.25             1.6      0.044   
4131            7.4              0.31         0.26             8.6      0.048   
6050            8.3              0.60         0.25             2.2      0.118   
3947            6.1              0.30         0.32             2.2      0.042   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
2362                 39.0                 144.0  0.99270  3.49       0.50   
4304                 24.0                 115.0  0.99210  3.39       0.59   
4131                 47.0                 206.0  0.99640  3.26       0.36   
6050                  9.0                  38.0  0.99616  3.15       0.53   
3947                 41.0                 142.0  0.98952  3.31       0.44   

      alcohol  quality   type  
2362     10.5        6  white  
4304     10.9        6  white  
4131      9.1        5  white  
6050      9.8        5    red  
3947     12.7        7  white

In [6]:
data.quality.value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [7]:
data.type.value_counts()

white    4898
red      1599
Name: type, dtype: int64

# Ejercicio 2.1

Mostrar la tabla de frecuencias de la calidad por tipo de vino.

In [8]:
(data 
  .groupby("type")
  .agg(frequency=( "type", "count")))

frequency
type            
red         1599
white       4898

In [9]:
df = data[["type","quality"]]
df


type  quality
0     white        6
1     white        6
2     white        6
3     white        6
4     white        6
...     ...      ...
6492    red        5
6493    red        6
6494    red        6
6495    red        5
6496    red        6

[6497 rows x 2 columns]

In [10]:
df1 = df.groupby(by = ["quality", "type"]).count()
df1

Empty DataFrame
Columns: []
Index: [(3, red), (3, white), (4, red), (4, white), (5, red), (5, white), (6, red), (6, white), (7, red), (7, white), (8, red), (8, white), (9, white)]

In [11]:
(df 
  .groupby(["type", "quality"])
  .agg(frequency=("type", "count")))

frequency
type  quality           
red   3               10
      4               53
      5              681
      6              638
      7              199
      8               18
white 3               20
      4              163
      5             1457
      6             2198
      7              880
      8              175
      9                5

# Ejercicio 2.2

Teniendo en cuenta todas las variables:

* Crear un objetivo binario para cada tipo de vino, haciendo la transformación necesaria para ingresar la información al modelo.
* Crear una SVM que prediga el tipo de vino
* Evalúe con F1, AUC-ROC y log-loss


Transformando la variable tipo de vino


In [12]:
data2 = data.rename(columns={'type':'tipo'})
data2.columns


Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'tipo'],
      dtype='object')

In [13]:
data = data2
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6493                 39.0                  51.0  0.99512  3.52       0.76   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality   tipo  
0         8.8        6  white  
1         9.5        6  white  
2        10.1        6  white  
3         9.9        6  white  
4         9.9        6  white  
...       ...      ...    ...  
6492     10.5        5    red  
6493     11.2        6    red  
6494     11.0        6    red  
6495     10.2        5    red  
6496     11.0        6    red  

[6497 rows x 13 columns]

In [14]:
data1 = data['tipo']= data.tipo.map({"white":0,"red":1})
data1


0       0
1       0
2       0
3       0
4       0
       ..
6492    1
6493    1
6494    1
6495    1
6496    1
Name: tipo, Length: 6497, dtype: int64

In [15]:
df = pd.DataFrame(data) 

In [16]:
df['tipo'] = data1 
df 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6493                 39.0                  51.0  0.99512  3.52       0.76   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  tipo  
0         8.8        6     0  
1         9.5        6     0  
2        10.1        6     0  
3         9.9        6     0  
4         9.9        6     0  
...       ...      ...   ...  
6492     10.5        5     1  
6493     11.2        6     1  
6494     11.0        6     1  
6495     10.2        5     1  
6496     11.0        6     1  

[6497 rows x 13 columns]

Crear SVM

In [28]:
X = df.drop(columns = 'tipo')
y = df['tipo']

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)

print ('Train set:', X_train.shape,  y_train.shape)

print ('Test set:', X_test.shape,  y_test.shape)


Train set: (5197, 12) (5197,)
Test set: (1300, 12) (1300,)


In [29]:
modelo = SVC(C = 100, kernel = 'linear', random_state=123)
modelo.fit(X_train, y_train)

SVC(C=100, kernel='linear', random_state=123)

In [30]:
predicciones = modelo.predict(X_test)
predicciones

array([1, 0, 0, ..., 0, 0, 0])

In [31]:
accuracy = accuracy_score(
            y_true    = y_test,
            y_pred    = predicciones,
            normalize = True
           )
print("")
print(f"El accuracy de test es: {100*accuracy}%")


El accuracy de test es: 98.6923076923077%


In [42]:
yhat = clf.predict(X_test)
yhat [0:5]


array([1, 0, 0, 0, 0])

In [54]:
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import roc_auc_score

print("Avg F1-score: %.4f" % f1_score(y_test, yhat))
print("Log_loss: %.4f" % log_loss(y_test, yhat))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat))


Avg F1-score: 0.9731
Log_loss: 0.4517
Prediccion: 0.9796


# Ejercicio 2.3

* Probar la SVM utilizando los diferentes kernels ('poly', 'rbf', 'sigmoid')
* Evalúe con F1, AUC-ROC y log-loss

Con Poly


In [51]:
modelo1 = SVC(C = 100, kernel = 'poly', random_state=123)
modelo1.fit(X_train, y_train)

SVC(C=100, kernel='poly', random_state=123)

In [52]:
predicciones1 = modelo1.predict(X_test)
predicciones1

array([1, 0, 1, ..., 1, 0, 0])

In [57]:
accuracy = accuracy_score(
            y_true    = y_test,
            y_pred    = predicciones1,
            normalize = True
           )
print("")
print(f"El accuracy de test es: {100*accuracy}%")


El accuracy de test es: 95.15384615384616%


In [59]:
yhat2 = modelo1.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat2, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat2))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat2))


Avg F1-score: 0.9515
Log_loss: 1.6738
Prediccion: 0.9339


Con rbf

In [60]:
modelo2 = SVC(C = 100, kernel = 'rbf', random_state=123)
modelo2.fit(X_train, y_train)

SVC(C=100, random_state=123)

In [61]:
predicciones2 = modelo2.predict(X_test)
predicciones2

array([1, 0, 0, ..., 1, 0, 0])

In [62]:
accuracy = accuracy_score(
            y_true    = y_test,
            y_pred    = predicciones2,
            normalize = True
           )
print("")
print(f"El accuracy de test es: {100*accuracy}%")


El accuracy de test es: 96.15384615384616%


In [63]:
yhat3 = modelo2.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat3, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat3))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat3))


Avg F1-score: 0.9608
Log_loss: 1.3284
Prediccion: 0.9299


Con sigmoid

In [64]:
modelo3 = SVC(C = 100, kernel = 'sigmoid', random_state=123)
modelo3.fit(X_train, y_train)

SVC(C=100, kernel='sigmoid', random_state=123)

In [65]:
predicciones3 = modelo3.predict(X_test)
predicciones3

array([0, 0, 0, ..., 0, 0, 0])

In [66]:
accuracy = accuracy_score(
            y_true    = y_test,
            y_pred    = predicciones3,
            normalize = True
           )
print("")
print(f"El accuracy de test es: {100*accuracy}%")


El accuracy de test es: 74.3076923076923%


In [67]:
yhat4 = modelo3.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat4, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat4))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat4))


Avg F1-score: 0.7425
Log_loss: 8.8739
Prediccion: 0.6503


# Ejercicio 2.4
* Utilizando el mejor SVM del punto anterior encontrar los parámetros que da el mejor rendimiento teniendo en cuenta los siguientes hiperparámetros
'C': [0.1, 1, 10, 100, 1000], 'gamma': [0.01, 0.001, 0.0001]
* Evalúe cada modelo con F1, AUC-ROC y log-loss

Nota: Para los valores de C y gamma, deben realizar todas las posibles combinaciones entre estas dos variables.

De acuerdo al análisis anterior, se obtienen mejores resultados provenientes de **"rbf"**

In [72]:
a = SVC(C = 0.1, gamma = 0.01, kernel = 'rbf', random_state=123)
a.fit(X_train, y_train)

yhat5 = a.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat5, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat5))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat5))


Avg F1-score: 0.9325
Log_loss: 2.2583
Prediccion: 0.8834


In [74]:
b = SVC(C = 0.1, gamma = 0.001, kernel = 'rbf', random_state=123)
b.fit(X_train, y_train)

yhat6 = b.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat6, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat6))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat6))

Avg F1-score: 0.9296
Log_loss: 2.3646
Prediccion: 0.8824


In [75]:
c = SVC(C = 0.1, gamma = 0.0001, kernel = 'rbf', random_state=123)
c.fit(X_train, y_train)

yhat7 = c.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat7, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat7))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat7))

Avg F1-score: 0.9187
Log_loss: 2.7100
Prediccion: 0.8630


In [76]:
d = SVC(C = 1, gamma = 0.01, kernel = 'rbf', random_state=123)
d.fit(X_train, y_train)

yhat8 = d.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat8, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat8))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat8))

Avg F1-score: 0.9457
Log_loss: 1.8332
Prediccion: 0.9075


In [77]:
e = SVC(C = 1, gamma = 0.001, kernel = 'rbf', random_state=123)
e.fit(X_train, y_train)

yhat9 = e.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat9, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat9))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat9))

Avg F1-score: 0.9391
Log_loss: 2.0458
Prediccion: 0.8949


In [78]:
f = SVC(C = 1, gamma = 0.0001, kernel = 'rbf', random_state=123)
f.fit(X_train, y_train)

yhat10 = f.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat10, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat10))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat10))

Avg F1-score: 0.9350
Log_loss: 2.1786
Prediccion: 0.8881


In [79]:
g = SVC(C = 10, gamma = 0.01, kernel = 'rbf', random_state=123)
g.fit(X_train, y_train)

yhat11 = g.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat11, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat11))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat11))

Avg F1-score: 0.9705
Log_loss: 1.0096
Prediccion: 0.9530


In [80]:
h = SVC(C = 10, gamma = 0.001, kernel = 'rbf', random_state=123)
h.fit(X_train, y_train)

yhat12 = h.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat12, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat12))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat12))

Avg F1-score: 0.9562
Log_loss: 1.4878
Prediccion: 0.9268


In [81]:
i = SVC(C = 10, gamma = 0.0001, kernel = 'rbf', random_state=123)
i.fit(X_train, y_train)

yhat13 = i.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat13, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat13))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat13))

Avg F1-score: 0.9472
Log_loss: 1.7801
Prediccion: 0.9085


In [82]:
j = SVC(C = 100, gamma = 0.01, kernel = 'rbf', random_state=123)
j.fit(X_train, y_train)

yhat14 = j.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat14, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat14))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat14))

Avg F1-score: 0.9814
Log_loss: 0.6376
Prediccion: 0.9697


In [83]:
k = SVC(C = 100, gamma = 0.001, kernel = 'rbf', random_state=123)
k.fit(X_train, y_train)

yhat15 = k.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat15, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat15))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat15))

Avg F1-score: 0.9845
Log_loss: 0.5314
Prediccion: 0.9749


In [84]:
l = SVC(C = 100, gamma = 0.0001, kernel = 'rbf', random_state=123)
l.fit(X_train, y_train)

yhat16 = l.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat16, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat16))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat16))

Avg F1-score: 0.9681
Log_loss: 1.0893
Prediccion: 0.9451


In [85]:
m = SVC(C = 1000, gamma = 0.01, kernel = 'rbf', random_state=123)
m.fit(X_train, y_train)

yhat17 = m.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat17, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat17))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat17))

Avg F1-score: 0.9823
Log_loss: 0.6111
Prediccion: 0.9745


In [86]:
n = SVC(C = 1000, gamma = 0.001, kernel = 'rbf', random_state=123)
n.fit(X_train, y_train)

yhat18 = n.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat18, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat18))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat18))

#Bajo estos hiperparámetros logra ser un modelo óptimo

Avg F1-score: 0.9900
Log_loss: 0.3454
Prediccion: 0.9827


In [87]:
r = SVC(C = 1000, gamma = 0.0001, kernel = 'rbf', random_state=123)
r.fit(X_train, y_train)

yhat19 = r.predict(X_test)
print("Avg F1-score: %.4f" % f1_score(y_test, yhat19, average='weighted'))
print("Log_loss: %.4f" % log_loss(y_test, yhat19))
print("Prediccion: %.4f" % roc_auc_score(y_test, yhat19))

Avg F1-score: 0.9869
Log_loss: 0.4517
Prediccion: 0.9775


# Ejercicio 2.5

Compare los resultados con todos los anteriores modelos y eliga ¿Cuál algoritmo con cuáles hiperparámetros es el que tiene mejor rendimiento según la puntuación F1, AUC-ROC y log-loss?

Después de realizar diversos contrastes entre hiperparámetros, se obtine que aquellos que proporcionan mejor informacion y puntuacion son:

C = 1000

Gamma = 0.001